### PR TITLE
style(components): unify line feed code to line feed

### PR DESCRIPTION
**Pull request by hitsuji-no-shippo**
Fix CRLF to LF.
Execute npm-script format command.

### CODE REVIEW

**Comment by thundermiracle** [comment]
@hitsuji-no-shippo 
Would you please tell me what's the purpose of this PR?

**Comment by hitsuji-no-shippo** [comment]
@thundermiracle 
I am studying English. I'm sorry to write hard-to-understand English.
Unification of line feed codes.
The line feed code was changed from CRLF to LF, and changed by executing the `yarn format` command.

**Comment by thundermiracle** [comment]
@hitsuji-no-shippo 
Thanks for your interest in this project!

I doubt whether this modification is necessary.  Both CRLF / LF work well in deployment.
Besides, all files are using CRLF include the files in your PR as I'm using Windows.

**Comment by davidcostadev** [comment]
I think that if the PR don't include anything new, It's not interesting. But I think to improve development its good use or one or another. We can use something like `.editorconfig` to help everyone speak the same idiom.

**Comment by thundermiracle** [comment]
@davidcostadev 
That's a great idea.
I'm using prettier to keep the project clean, but perhaps .editorconfig is necessary too.

**Comment by thundermiracle** [comment]
@hitsuji-no-shippo 
I'm going to close this PR. 
You can consider contribute #78 instead.

**Pull request closed without merging**
